#!/usr/bin/env python3
"""Download the CC0 texture sets and HDRIs used by scoot would from Poly Haven.

All Poly Haven assets are CC0 (public domain): https://polyhaven.com/license
The downloaded files are committed to assets/ so builds do not need network access;
run this script again only to refresh or add assets.

usage: python3 tools/fetch_assets.py [--res 1k]
"""
import argparse
import json
import os
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEX_DIR = os.path.join(ROOT, "assets", "textures")
HDRI_DIR = os.path.join(ROOT, "assets", "hdri")

# poly haven id -> local short name
TEXTURES = {
    "concrete_floor_02": "concrete_smooth",
    "brushed_concrete": "concrete_park",
    "concrete_floor_worn_001": "concrete_worn",
    "concrete_wall_008": "concrete_wall",
    "asphalt_02": "asphalt",
    "pavement_02": "pavement",
    "large_grey_tiles": "plaza_tiles",
    "plywood": "plywood",
    "wood_floor_deck": "wood_deck",
    "metal_plate": "metal_plate",
    "green_metal_rust": "metal_rust",
    "corrugated_iron": "corrugated",
    "painted_metal_shutter": "shutter",
    "red_brick_03": "brick_red",
    "beige_wall_001": "plaster_beige",
    "white_plaster_02": "plaster_white",
    "factory_wall": "factory_wall",
    "grey_roof_01": "roof_grey",
    "leafy_grass": "grass",
    "dirt_floor": "dirt",
    "bark_brown_02": "bark",
    "rubber_tiles": "rubber",
    "gravel_concrete": "gravel_concrete",
}
MAPS = {"Diffuse": "diff", "nor_gl": "nrm", "arm": "arm"}

HDRIS = {
    "kloofendal_48d_partly_cloudy_puresky": ("day", "2k"),
    "industrial_sunset_puresky": ("sunset", "2k"),
    "kloofendal_43d_clear_puresky": ("clear", "1k"),
    "overcast_soil_puresky": ("overcast", "1k"),
    "moonless_golf": ("night", "1k"),
}


UA = {"User-Agent": "scoot-would-asset-fetch/1.0 (+https://polyhaven.com)"}


def get_json(url):
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60) as r:
        return json.loads(r.read().decode("utf-8"))


def download(url, path):
    if os.path.exists(path) and os.path.getsize(path) > 0:
        return False
    tmp = path + ".part"
    with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=300) as r, open(tmp, "wb") as f:
        while True:
            chunk = r.read(1 << 16)
            if not chunk:
                break
            f.write(chunk)
    os.replace(tmp, path)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--res", default="1k")
    args = ap.parse_args()
    os.makedirs(TEX_DIR, exist_ok=True)
    os.makedirs(HDRI_DIR, exist_ok=True)
    manifest = []
    for pid, name in TEXTURES.items():
        files = get_json(f"https://api.polyhaven.com/files/{pid}")
        for key, suffix in MAPS.items():
            entry = files.get(key, {}).get(args.res, {}).get("jpg")
            if not entry:
                print(f"  ! {pid}: no {key} {args.res} jpg", file=sys.stderr)
                continue
            out = os.path.join(TEX_DIR, f"{name}_{suffix}.jpg")
            if download(entry["url"], out):
                print(f"  + {out}")
        manifest.append(f"| textures/{name}_* | https://polyhaven.com/a/{pid} | CC0 |")
    for pid, (name, res) in HDRIS.items():
        files = get_json(f"https://api.polyhaven.com/files/{pid}")
        entry = files["hdri"][res]["hdr"]
        out = os.path.join(HDRI_DIR, f"{name}.hdr")
        if download(entry["url"], out):
            print(f"  + {out}")
        manifest.append(f"| hdri/{name}.hdr | https://polyhaven.com/a/{pid} | CC0 |")
    with open(os.path.join(ROOT, "assets", "SOURCES.md"), "w") as f:
        f.write("# Asset sources\n\n")
        f.write("Photographic textures and HDRIs come from [Poly Haven](https://polyhaven.com) and are CC0 (public domain).\n")
        f.write("Models, animations, sounds and level data are generated by the tools in `tools/` and are part of this project.\n\n")
        f.write("| file | source | license |\n|---|---|---|\n")
        f.write("\n".join(manifest) + "\n")
    print("done")


if __name__ == "__main__":
    main()
